version: "3"
services:
    portfolio:
        image: "qtsky89/portfolio:1.1.1"
        ports:
            - "80:80"
        volumes:
            - apache_logs:/home1/irteam/apache/logs
            - /home/irteam/apps/portfolio/django/django_project/my_settings.py:/home/irteam/apps/portfolio/django/django_project/my_settings.py
volumes:
    apache_logs:
        external: true
