version: "3"
services:
    portfolio:
        image: "qtsky89/portfolio:1.3.1"
        ports:
            - "80:80"
        volumes:
            - apache_logs:/home1/irteam/apache/logs
            - type: bind
              source: ./my_settings.py
              target: /home/irteam/apps/portfolio/django/django_project/my_settings.py
volumes:
    apache_logs:
        external: true
