FROM qtsky89/portfolio_base:1.0.0

LABEL maintainer="Wonhee Jang <Qtsky89@gmail.com>"
LABEL description="Dockerfile for portfolio"

# git clone
RUN git clone -b master https://oss.navercorp.com/qtsky89/portfolio /home1/irteam/apps/portfolio

# build vue
