# Generated by Django 3.1.6 on 2021-02-13 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('image', models.CharField(default='', max_length=4096)),
                ('constraint', models.CharField(default='', max_length=256)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
